// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupJoinRequestBuf.proto

#ifndef PROTOBUF_GroupJoinRequestBuf_2eproto__INCLUDED
#define PROTOBUF_GroupJoinRequestBuf_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace huizhi {
namespace im {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_GroupJoinRequestBuf_2eproto();
void protobuf_AssignDesc_GroupJoinRequestBuf_2eproto();
void protobuf_ShutdownFile_GroupJoinRequestBuf_2eproto();

class GroupJoinRequest;
class GroupJoinResponse;

// ===================================================================

class GroupJoinRequest : public ::google::protobuf::Message {
 public:
  GroupJoinRequest();
  virtual ~GroupJoinRequest();

  GroupJoinRequest(const GroupJoinRequest& from);

  inline GroupJoinRequest& operator=(const GroupJoinRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GroupJoinRequest& default_instance();

  void Swap(GroupJoinRequest* other);

  // implements Message ----------------------------------------------

  GroupJoinRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GroupJoinRequest& from);
  void MergeFrom(const GroupJoinRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 groupId = 1;
  inline bool has_groupid() const;
  inline void clear_groupid();
  static const int kGroupIdFieldNumber = 1;
  inline ::google::protobuf::int32 groupid() const;
  inline void set_groupid(::google::protobuf::int32 value);

  // required int32 userId = 2;
  inline bool has_userid() const;
  inline void clear_userid();
  static const int kUserIdFieldNumber = 2;
  inline ::google::protobuf::int32 userid() const;
  inline void set_userid(::google::protobuf::int32 value);

  // required int32 type = 3;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 3;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.huizhi.im.protobuf.GroupJoinRequest)
 private:
  inline void set_has_groupid();
  inline void clear_has_groupid();
  inline void set_has_userid();
  inline void clear_has_userid();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 groupid_;
  ::google::protobuf::int32 userid_;
  ::google::protobuf::int32 type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_GroupJoinRequestBuf_2eproto();
  friend void protobuf_AssignDesc_GroupJoinRequestBuf_2eproto();
  friend void protobuf_ShutdownFile_GroupJoinRequestBuf_2eproto();

  void InitAsDefaultInstance();
  static GroupJoinRequest* default_instance_;
};
// -------------------------------------------------------------------

class GroupJoinResponse : public ::google::protobuf::Message {
 public:
  GroupJoinResponse();
  virtual ~GroupJoinResponse();

  GroupJoinResponse(const GroupJoinResponse& from);

  inline GroupJoinResponse& operator=(const GroupJoinResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GroupJoinResponse& default_instance();

  void Swap(GroupJoinResponse* other);

  // implements Message ----------------------------------------------

  GroupJoinResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GroupJoinResponse& from);
  void MergeFrom(const GroupJoinResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // required int32 userId = 2;
  inline bool has_userid() const;
  inline void clear_userid();
  static const int kUserIdFieldNumber = 2;
  inline ::google::protobuf::int32 userid() const;
  inline void set_userid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.huizhi.im.protobuf.GroupJoinResponse)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_userid();
  inline void clear_has_userid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 result_;
  ::google::protobuf::int32 userid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_GroupJoinRequestBuf_2eproto();
  friend void protobuf_AssignDesc_GroupJoinRequestBuf_2eproto();
  friend void protobuf_ShutdownFile_GroupJoinRequestBuf_2eproto();

  void InitAsDefaultInstance();
  static GroupJoinResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// GroupJoinRequest

// required int32 groupId = 1;
inline bool GroupJoinRequest::has_groupid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GroupJoinRequest::set_has_groupid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GroupJoinRequest::clear_has_groupid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GroupJoinRequest::clear_groupid() {
  groupid_ = 0;
  clear_has_groupid();
}
inline ::google::protobuf::int32 GroupJoinRequest::groupid() const {
  return groupid_;
}
inline void GroupJoinRequest::set_groupid(::google::protobuf::int32 value) {
  set_has_groupid();
  groupid_ = value;
}

// required int32 userId = 2;
inline bool GroupJoinRequest::has_userid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GroupJoinRequest::set_has_userid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GroupJoinRequest::clear_has_userid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GroupJoinRequest::clear_userid() {
  userid_ = 0;
  clear_has_userid();
}
inline ::google::protobuf::int32 GroupJoinRequest::userid() const {
  return userid_;
}
inline void GroupJoinRequest::set_userid(::google::protobuf::int32 value) {
  set_has_userid();
  userid_ = value;
}

// required int32 type = 3;
inline bool GroupJoinRequest::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GroupJoinRequest::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GroupJoinRequest::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GroupJoinRequest::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 GroupJoinRequest::type() const {
  return type_;
}
inline void GroupJoinRequest::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}

// -------------------------------------------------------------------

// GroupJoinResponse

// required int32 result = 1;
inline bool GroupJoinResponse::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GroupJoinResponse::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GroupJoinResponse::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GroupJoinResponse::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 GroupJoinResponse::result() const {
  return result_;
}
inline void GroupJoinResponse::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// required int32 userId = 2;
inline bool GroupJoinResponse::has_userid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GroupJoinResponse::set_has_userid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GroupJoinResponse::clear_has_userid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GroupJoinResponse::clear_userid() {
  userid_ = 0;
  clear_has_userid();
}
inline ::google::protobuf::int32 GroupJoinResponse::userid() const {
  return userid_;
}
inline void GroupJoinResponse::set_userid(::google::protobuf::int32 value) {
  set_has_userid();
  userid_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace im
}  // namespace huizhi
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GroupJoinRequestBuf_2eproto__INCLUDED
