// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UnReadInfoBuf.proto

#ifndef PROTOBUF_UnReadInfoBuf_2eproto__INCLUDED
#define PROTOBUF_UnReadInfoBuf_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace huizhi {
namespace im {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UnReadInfoBuf_2eproto();
void protobuf_AssignDesc_UnReadInfoBuf_2eproto();
void protobuf_ShutdownFile_UnReadInfoBuf_2eproto();

class UnReadInfo;
class Counter;

// ===================================================================

class UnReadInfo : public ::google::protobuf::Message {
 public:
  UnReadInfo();
  virtual ~UnReadInfo();

  UnReadInfo(const UnReadInfo& from);

  inline UnReadInfo& operator=(const UnReadInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UnReadInfo& default_instance();

  void Swap(UnReadInfo* other);

  // implements Message ----------------------------------------------

  UnReadInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UnReadInfo& from);
  void MergeFrom(const UnReadInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 unReadSize = 1;
  inline bool has_unreadsize() const;
  inline void clear_unreadsize();
  static const int kUnReadSizeFieldNumber = 1;
  inline ::google::protobuf::int32 unreadsize() const;
  inline void set_unreadsize(::google::protobuf::int32 value);

  // repeated .com.huizhi.im.protobuf.Counter uids = 2;
  inline int uids_size() const;
  inline void clear_uids();
  static const int kUidsFieldNumber = 2;
  inline const ::com::huizhi::im::protobuf::Counter& uids(int index) const;
  inline ::com::huizhi::im::protobuf::Counter* mutable_uids(int index);
  inline ::com::huizhi::im::protobuf::Counter* add_uids();
  inline const ::google::protobuf::RepeatedPtrField< ::com::huizhi::im::protobuf::Counter >&
      uids() const;
  inline ::google::protobuf::RepeatedPtrField< ::com::huizhi::im::protobuf::Counter >*
      mutable_uids();

  // @@protoc_insertion_point(class_scope:com.huizhi.im.protobuf.UnReadInfo)
 private:
  inline void set_has_unreadsize();
  inline void clear_has_unreadsize();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::com::huizhi::im::protobuf::Counter > uids_;
  ::google::protobuf::int32 unreadsize_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_UnReadInfoBuf_2eproto();
  friend void protobuf_AssignDesc_UnReadInfoBuf_2eproto();
  friend void protobuf_ShutdownFile_UnReadInfoBuf_2eproto();

  void InitAsDefaultInstance();
  static UnReadInfo* default_instance_;
};
// -------------------------------------------------------------------

class Counter : public ::google::protobuf::Message {
 public:
  Counter();
  virtual ~Counter();

  Counter(const Counter& from);

  inline Counter& operator=(const Counter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Counter& default_instance();

  void Swap(Counter* other);

  // implements Message ----------------------------------------------

  Counter* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Counter& from);
  void MergeFrom(const Counter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 uid = 1;
  inline bool has_uid() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 1;
  inline ::google::protobuf::int32 uid() const;
  inline void set_uid(::google::protobuf::int32 value);

  // required int32 count = 2;
  inline bool has_count() const;
  inline void clear_count();
  static const int kCountFieldNumber = 2;
  inline ::google::protobuf::int32 count() const;
  inline void set_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.huizhi.im.protobuf.Counter)
 private:
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_count();
  inline void clear_has_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 uid_;
  ::google::protobuf::int32 count_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_UnReadInfoBuf_2eproto();
  friend void protobuf_AssignDesc_UnReadInfoBuf_2eproto();
  friend void protobuf_ShutdownFile_UnReadInfoBuf_2eproto();

  void InitAsDefaultInstance();
  static Counter* default_instance_;
};
// ===================================================================


// ===================================================================

// UnReadInfo

// required int32 unReadSize = 1;
inline bool UnReadInfo::has_unreadsize() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UnReadInfo::set_has_unreadsize() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UnReadInfo::clear_has_unreadsize() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UnReadInfo::clear_unreadsize() {
  unreadsize_ = 0;
  clear_has_unreadsize();
}
inline ::google::protobuf::int32 UnReadInfo::unreadsize() const {
  return unreadsize_;
}
inline void UnReadInfo::set_unreadsize(::google::protobuf::int32 value) {
  set_has_unreadsize();
  unreadsize_ = value;
}

// repeated .com.huizhi.im.protobuf.Counter uids = 2;
inline int UnReadInfo::uids_size() const {
  return uids_.size();
}
inline void UnReadInfo::clear_uids() {
  uids_.Clear();
}
inline const ::com::huizhi::im::protobuf::Counter& UnReadInfo::uids(int index) const {
  return uids_.Get(index);
}
inline ::com::huizhi::im::protobuf::Counter* UnReadInfo::mutable_uids(int index) {
  return uids_.Mutable(index);
}
inline ::com::huizhi::im::protobuf::Counter* UnReadInfo::add_uids() {
  return uids_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::com::huizhi::im::protobuf::Counter >&
UnReadInfo::uids() const {
  return uids_;
}
inline ::google::protobuf::RepeatedPtrField< ::com::huizhi::im::protobuf::Counter >*
UnReadInfo::mutable_uids() {
  return &uids_;
}

// -------------------------------------------------------------------

// Counter

// required int32 uid = 1;
inline bool Counter::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Counter::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Counter::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Counter::clear_uid() {
  uid_ = 0;
  clear_has_uid();
}
inline ::google::protobuf::int32 Counter::uid() const {
  return uid_;
}
inline void Counter::set_uid(::google::protobuf::int32 value) {
  set_has_uid();
  uid_ = value;
}

// required int32 count = 2;
inline bool Counter::has_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Counter::set_has_count() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Counter::clear_has_count() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Counter::clear_count() {
  count_ = 0;
  clear_has_count();
}
inline ::google::protobuf::int32 Counter::count() const {
  return count_;
}
inline void Counter::set_count(::google::protobuf::int32 value) {
  set_has_count();
  count_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace im
}  // namespace huizhi
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UnReadInfoBuf_2eproto__INCLUDED
