
var cardAnalysis = cardAnalysis?cardAnalysis:{};

cardAnalysis.CardName = 
{
	CARD_NAME_NULL 					: -1,
	CARD_NAME_SANHUALIU 			: 0,		// 三花六
	CARD_NAME_SANHUASHI 			: 1,		// 三花十
	CARD_NAME_LINGDIAN 				: 2, 		// 零点
	CARD_NAME_DINGQIZHOU 			: 3,		// 丁七皱
	CARD_NAME_FUJIUZHOU 			: 4,		// 斧九皱
	CARD_NAME_SHUANGHUASHI 			: 5,		// 双花十
	CARD_NAME_SILIUTING 			: 6,		// 四六挺
	CARD_NAME_YIDIAN 				: 7,		// 一点
	CARD_NAME_DINGBAYI 				: 8,		// 丁八一
	CARD_NAME_WULIUYI 				: 9,		// 五六一
	CARD_NAME_FUSHIYI 				: 10,		// 斧十一
	CARD_NAME_CHANGSANYI 			: 11,		// 长三一
	CARD_NAME_SIQIYI 				: 12,		// 四七一
	CARD_NAME_MEISHIYI 				: 13,		// 梅十一
	CARD_NAME_HESHIYI 				: 14,		// 和十一
	CARD_NAME_RENSHIYI 				: 15,		// 人十一
	CARD_NAME_DIJIUWANG 			: 16,		// 地九王
	CARD_NAME_ERDIAN 				: 17,		// 二点
	CARD_NAME_WUQIER 				: 18,		// 五七二
	CARD_NAME_DINGJIUER 			: 19,		// 丁九二
	CARD_NAME_GAOYAOER 				: 20,		// 膏药二
	CARD_NAME_ERLIUER 				: 21,		// 二六二
	CARD_NAME_SIBAER 				: 22,		// 四八二
	CARD_NAME_HESHIER 				: 23,		// 和十二
	CARD_NAME_RENSHIER 				: 24,		// 人十二
	CARD_NAME_DISHIER 				: 25,		// 地十二
	CARD_NAME_TIANSHIER 			: 26,		// 天十二
	CARD_NAME_SANDIAN 				: 27, 		// 三点
	CARD_NAME_WUBASAN 				: 28,		// 五八三
	CARD_NAME_LIUQISAN 				: 29,		// 六七三
	CARD_NAME_TIAOSHISAN 			: 30,		// 笤十三
	CARD_NAME_CHANGSHISAN 			: 31,		// 长十三
	CARD_NAME_SIJIUSAN 				: 32,		// 四九三
	CARD_NAME_MEISHISAN 			: 33,		// 梅十三
	CARD_NAME_HESHISAN 				: 34,		// 和十三
	CARD_NAME_RENSHISAN 			: 35,		// 人十三
	CARD_NAME_DIFUSAN 				: 36,		// 地斧三
	CARD_NAME_TIANFUSAN 			: 37,		// 天斧三
	CARD_NAME_SIDIAN 				: 38, 		// 四点
	CARD_NAME_WUJIUSI 				: 39,		// 五九四
	CARD_NAME_SHUANGHUAQI 			: 40,		// 双花七
	CARD_NAME_LIUBASI 				: 41,		// 六八四
	CARD_NAME_DINGFUSI 				: 42,		// 丁斧四
	CARD_NAME_CHANGSHISI 			: 43,		// 长十四
	CARD_NAME_MEISHISI 				: 44,		// 梅十四
	CARD_NAME_HESHISI 				: 45,		// 和十四
	CARD_NAME_RENSHISI 				: 46,		// 人十四
	CARD_NAME_TIANDIGONGZI 			: 47,		// 天地公子
	CARD_NAME_WUDIAN 				: 48, 		// 五点
	CARD_NAME_QIBAWU 				: 49,		// 七八五
	CARD_NAME_GAOYAOWU 				: 50,		// 膏药五
	CARD_NAME_MAOJIUWU 				: 51,		// 猫九五
	CARD_NAME_TIAOSHIWU 			: 52,		// 笤十五
	CARD_NAME_CHANGSANWU 			: 53,		// 长三五
	CARD_NAME_BANFUWU 				: 54,		// 板斧五
	CARD_NAME_MEISHIWU 				: 55,		// 梅十五
	CARD_NAME_HEFUWU 				: 56,		// 和斧五
	CARD_NAME_RENSHIWU 				: 57,		// 人十五
	CARD_NAME_DIDINGWU 				: 58,		// 地丁五
	CARD_NAME_TIANDINGWU 			: 59,		// 天丁五
	CARD_NAME_LIUDIAN 				: 60, 		// 六点
	CARD_NAME_QIJIULIU 				: 61,		// 七九六
	CARD_NAME_GAOYAOLIU 			: 62,		// 膏药六
	CARD_NAME_TIAOSHILIU 			: 63,		// 笤十六
	CARD_NAME_FUWULIU 				: 64,		// 斧五六
	CARD_NAME_CHANGSANLIU 			: 65,		// 长三六
	CARD_NAME_MEISHILIU 			: 66,		// 梅十六
	CARD_NAME_YUANBAOLIU 			: 67,		// 元宝六
	CARD_NAME_DIGUANLIU 			: 68,		// 地官六
	CARD_NAME_TIANGUANLIU 			: 69,		// 天官六
	CARD_NAME_QIDIAN 				: 70, 		// 七点
	CARD_NAME_FEIZHOUQI 			: 71,		// 非洲七
	CARD_NAME_TIAOSHIQI 			: 72,		// 笤十七
	CARD_NAME_FUMAOQI 				: 73,		// 斧猫七
	CARD_NAME_FUCHANGQI 			: 74,		// 斧长七
	CARD_NAME_DINGBANQI 			: 75,		// 丁板七
	CARD_NAME_MEISHIQI 				: 76,		// 梅十七
	CARD_NAME_DINGHEQI 				: 77,		// 丁和七
	CARD_NAME_SUZHOUQI 				: 78,		// 苏州七
	CARD_NAME_DIGUANQI 				: 79,		// 地官七
	CARD_NAME_TIANGUANQI 			: 80,		// 天官七
	CARD_NAME_BADIAN 				: 81,		// 八点
	CARD_NAME_DINGWUBA 				: 82,		// 丁五八
	CARD_NAME_TIAOSHIBA 			: 83,		// 笤十八
	CARD_NAME_FUQIBA 				: 84,		// 斧七八
	CARD_NAME_MEISHIBA 				: 85,		// 梅十八
	CARD_NAME_HEGUANBA 				: 86,		// 和官八
	CARD_NAME_RENSHIBA 				: 87,		// 人十八
	CARD_NAME_DIGUANBA 				: 88,		// 地官八
	CARD_NAME_TIANGUANBA 			: 89,		// 天官八
	CARD_NAME_JIUDIAN 				: 90, 		// 九点
	CARD_NAME_DINGMAOJIU 			: 91,		// 丁猫九
	CARD_NAME_TIAOSHIJIU 			: 92,		// 笤十九
	CARD_NAME_WULONGJIU 			: 93,		// 乌龙九
	CARD_NAME_DINGCHANGJIU 			: 94,		// 丁长九
	CARD_NAME_BANWUJIU 				: 95,		// 板五九
	CARD_NAME_MEISHIJIU 			: 96,		// 梅十九
	CARD_NAME_HEGUANJIU 			: 97,		// 和官九
	CARD_NAME_RENGUANJIU 			: 98,		// 人官九
	CARD_NAME_DIGUANJIU 			: 99,		// 地官九
	CARD_NAME_TIANGUANJIU 			: 100,		// 天官九
	CARD_NAME_DIHEIGANG 			: 101,		// 地黑杠
	CARD_NAME_DIHONGGANG 			: 102,		// 地红杠
	CARD_NAME_TIANHEIGANG			: 103,		// 天黑杠
	CARD_NAME_TIANHONGGANG 			: 104,		// 天红杠
	CARD_NAME_WANG 					: 105,		// 王
	CARD_NAME_SILAN					: 106,		// 四滥
	CARD_NAME_XIAYAODUI				: 107,		// 下腰对
	CARD_NAME_ZHONGSANDUI			: 108,		// 中三对
	CARD_NAME_HEPAIDUI				: 109,		// 和牌对
	CARD_NAME_RENPAIDUI				: 110,		// 人牌对
	CARD_NAME_DIPAIDUI				: 111,		// 地牌对
	CARD_NAME_TIANPAIDUI			: 112,		// 天牌对
	CARD_NAME_DINGERHUANG 			: 113,		// 丁二皇
};

cardAnalysis.CardGrade =
{
	CARD_GRADE_NULL 				: -1,
	CARD_GRADE_SANHUALIU 			: 0,		// 三花六
	CARD_GRADE_SANHUASHI 			: 0,		// 三花十
	CARD_GRADE_LINGDIAN 			: 1,		// 零点
	CARD_GRADE_DINGQIZHOU 			: 2,		// 丁七皱
	CARD_GRADE_FUJIUZHOU 			: 3,		// 斧九皱
	CARD_GRADE_SHUANGHUASHI			: 4,		// 双花十
	CARD_GRADE_SILIUTING 			: 5,		// 四六挺
	CARD_GRADE_YIDIAN 				: 6, 		// 一点
	CARD_GRADE_DINGBAYI 			: 7,		// 丁八一
	CARD_GRADE_WULIUYI 				: 8,		// 五六一
	CARD_GRADE_FUSHIYI 				: 8,		// 斧十一	
	CARD_GRADE_CHANGSANYI 			: 9,		// 长三一
	CARD_GRADE_SIQIYI 				: 9,		// 四七一
	CARD_GRADE_MEISHIYI 			: 9,		// 梅十一 
	CARD_GRADE_HESHIYI 				: 10,		// 和十一
	CARD_GRADE_RENSHIYI 			: 11,		// 人十一
	CARD_GRADE_DIJIUWANG 			: 12,		// 地九王
	CARD_GRADE_ERDIAN 				: 13, 		// 二点
	CARD_GRADE_WUQIER 				: 14,		// 五七二
	CARD_GRADE_DINGJIUER 			: 14,		// 丁九二	
	CARD_GRADE_GAOYAOER 			: 15,		// 膏药二
	CARD_GRADE_ERLIUER 				: 16,		// 二六二
	CARD_GRADE_SIBAER 				: 16,		// 四八二	
	CARD_GRADE_HESHIER 				: 17,		// 和十二
	CARD_GRADE_RENSHIER 			: 18,		// 人十二
	CARD_GRADE_DISHIER 				: 19,		// 地十二
	CARD_GRADE_TIANSHIER 			: 20,		// 天十二
	CARD_GRADE_SANDIAN 				: 21, 		// 三点
	CARD_GRADE_WUBASAN 				: 22,		// 五八三
	CARD_GRADE_LIUQISAN 			: 23,		// 六七三
	CARD_GRADE_TIAOSHISAN 			: 23,		// 笤十三	
	CARD_GRADE_CHANGSHISAN 			: 24,		// 长十三
	CARD_GRADE_SIJIUSAN 			: 24,		// 四九三
	CARD_GRADE_MEISHISAN 			: 24,		// 梅十三	
	CARD_GRADE_HESHISAN 			: 25,		// 和十三
	CARD_GRADE_RENSHISAN 			: 26,		// 人十三
	CARD_GRADE_DIFUSAN 				: 27,		// 地斧三
	CARD_GRADE_TIANFUSAN 			: 28,		// 天斧三
	CARD_GRADE_SIDIAN 				: 29, 		// 四点
	CARD_GRADE_WUJIUSI 				: 30,		// 五九四
	CARD_GRADE_SHUANGHUAQI 			: 31,		// 双花七
	CARD_GRADE_LIUBASI 				: 31,		// 六八四
	CARD_GRADE_DINGFUSI 			: 31,		// 丁斧四	
	CARD_GRADE_CHANGSHISI 			: 32,		// 长十四
	CARD_GRADE_MEISHISI 			: 32,		// 梅十四	
	CARD_GRADE_HESHISI 				: 33,		// 和十四
	CARD_GRADE_RENSHISI 			: 34,		// 人十四
	CARD_GRADE_TIANDIGONGZI			: 35,		// 天地公子
	CARD_GRADE_WUDIAN 				: 36, 		// 五点
	CARD_GRADE_QIBAWU 				: 37,		// 七八五
	CARD_GRADE_GAOYAOWU 			: 38,		// 膏药五
	CARD_GRADE_MAOJIUWU 			: 38,		// 猫九五
	CARD_GRADE_TIAOSHIWU 			: 38,		// 笤十五 	
	CARD_GRADE_CHANGSANWU 			: 39,		// 长三五
	CARD_GRADE_BANFUWU 				: 39,		// 板斧五
	CARD_GRADE_MEISHIWU 			: 39,		// 梅十五	
	CARD_GRADE_HEFUWU 				: 40,		// 和斧五
	CARD_GRADE_RENSHIWU 			: 41,		// 人十五
	CARD_GRADE_DIDINGWU 			: 41,		// 地丁五
	CARD_GRADE_TIANDINGWU 			: 43,		// 天丁五
	CARD_GRADE_LIUDIAN 				: 44, 		// 六点
	CARD_GRADE_QIJIULIU 			: 45,		// 七九六
	CARD_GRADE_GAOYAOLIU 			: 46,		// 膏药六
	CARD_GRADE_TIAOSHILIU 			: 46,		// 笤十六
	CARD_GRADE_FUWULIU 				: 46,		// 斧五六	
	CARD_GRADE_CHANGSANLIU 			: 47,		// 长三六
	CARD_GRADE_MEISHILIU 			: 47,		// 梅十六
	CARD_GRADE_YUANBAOLIU 			: 48,		// 元宝六
	CARD_GRADE_DIGUANLIU 			: 49,		// 地官六
	CARD_GRADE_TIANGUANLIU 			: 50,		// 天官六
	CARD_GRADE_QIDIAN 				: 51, 		// 七点
	CARD_GRADE_FEIZHOUQI 			: 52,		// 非洲七
	CARD_GRADE_TIAOSHIQI 			: 53,		// 笤十七
	CARD_GRADE_FUMAOQI 				: 53,		// 斧猫七 
	CARD_GRADE_FUCHANGQI 			: 54,		// 斧长七
	CARD_GRADE_DINGBANQI 			: 54,		// 丁板七
	CARD_GRADE_MEISHIQI 			: 54,		// 梅十七
	CARD_GRADE_DINGHEQI 			: 55,		// 丁和七
	CARD_GRADE_SUZHOUQI 			: 56,		// 苏州七
	CARD_GRADE_DIGUANQI 			: 57,		// 地官七
	CARD_GRADE_TIANGUANQI 			: 58,		// 天官七
	CARD_GRADE_BADIAN 				: 59, 		// 八点
	CARD_GRADE_DINGWUBA 			: 60,		// 丁五八
	CARD_GRADE_TIAOSHIBA 			: 61,		// 笤十八
	CARD_GRADE_FUQIBA 				: 61,		// 斧七八 
	CARD_GRADE_MEISHIBA 			: 62,		// 梅十八
	CARD_GRADE_HEGUANBA 			: 63,		// 和官八
	CARD_GRADE_RENSHIBA 			: 64,		// 人十八
	CARD_GRADE_DIGUANBA 			: 65,		// 地官八
	CARD_GRADE_TIANGUANBA 			: 66,		// 天官八
	CARD_GRADE_JIUDIAN 				: 67, 		// 九点
	CARD_GRADE_DINGMAOJIU 			: 68,		// 丁猫九
	CARD_GRADE_TIAOSHIJIU 			: 68,		// 笤十九
	CARD_GRADE_WULONGJIU			: 68,		// 乌龙九
	CARD_GRADE_DINGCHANGJIU			: 69,		// 丁长九
	CARD_GRADE_BANWUJIU 			: 69,		// 板五九
	CARD_GRADE_MEISHIJIU			: 69,		// 梅十九
	CARD_GRADE_HEGUANJIU 			: 70,		// 和官九
	CARD_GRADE_RENGUANJIU 			: 71,		// 人官九
	CARD_GRADE_DIGUANJIU 			: 72,		// 地官九
	CARD_GRADE_TIANGUANJIU 			: 73,		// 天官九
	CARD_GRADE_DIHEIGANG 			: 74,		// 地黑杠
	CARD_GRADE_DIHONGGANG			: 74,		// 地红杠
	CARD_GRADE_TIANHEIGANG			: 75,		// 天黑杠
	CARD_GRADE_TIANHONGGANG			: 75,		// 天红杠
	CARD_GRADE_WANG 				: 76,		// 王
	CARD_GRADE_SILAN				: 77,		// 四滥
	CARD_GRADE_XIAYAODUI			: 78,		// 下腰对
	CARD_GRADE_ZHONGSANDUI			: 79,		// 中三对
	CARD_GRADE_HEPAIDUI				: 80,		// 和牌对
	CARD_GRADE_RENPAIDUI			: 81,		// 人牌对
	CARD_GRADE_DIPAIDUI				: 82,		// 地牌对
	CARD_GRADE_TIANPAIDUI			: 83,		// 天牌对
	CARD_GRADE_DINGERHUANG 			: 84,		// 丁二皇
};
